// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import ImagePreviewController from "./image_preview_controller"
application.register("image-preview", ImagePreviewController)

import RecommendationPopupController from "./recommendation_popup_controller"
application.register("recommendation-popup", RecommendationPopupController)

import TabsController from "./tabs_controller"
application.register("tabs", TabsController)