AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2
  Exclude:
    - 'vendor/**/*'
    - 'node_modules/**/*'
    - 'db/schema.rb'
    - 'db/migrate/*.rb'
    - 'bin/*'

#Rails:
#  Enabled: true

plugins:
  - rubocop-rails
  
# 必要最小限の無効化
Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

# メトリクス系を適度に設定
Metrics/BlockLength:
  Max: 25
  Exclude:
    - 'spec/**/*'
    - 'config/routes.rb'

Layout/LineLength:
  Max: 100

Metrics/MethodLength:
  Max: 15

Metrics/AbcSize:
  Max: 15

# 命名規則
Naming/VariableNumber:
  Enabled: false